spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

---

mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  configuration:
    jdbc-type-for-null: "NULL"
    map-underscore-to-camel-case: true

logging:
  level:
    com.moira.itda.domain.account.delete.mapper: DEBUG
    com.moira.itda.domain.account.login.mapper: DEBUG
    com.moira.itda.domain.account.logout.mapper: DEBUG
    com.moira.itda.domain.account.signup.mapper: DEBUG
    com.moira.itda.domain.admin.gacha.mapper: DEBUG
    com.moira.itda.domain.admin.support.mapper: DEBUG
    com.moira.itda.domain.admin_user.mapper: DEBUG
    com.moira.itda.domain.admin_user_report.mapper: DEBUG
    com.moira.itda.domain.chat.detail.mapper: DEBUG
    com.moira.itda.domain.chat.history.mapper: DEBUG
    com.moira.itda.domain.common.identify.mapper: DEBUG
    com.moira.itda.domain.common.image.mapper: DEBUG
    com.moira.itda.domain.common.refresh.mapper: DEBUG
    com.moira.itda.domain.gacha.common.mapper: DEBUG
    com.moira.itda.domain.gacha.detail.mapper: DEBUG
    com.moira.itda.domain.gacha.list.mapper: DEBUG
    com.moira.itda.domain.gacha.pick.mapper: DEBUG
    com.moira.itda.domain.notification.mapper: DEBUG
    com.moira.itda.domain.suggest.add.mapper: DEBUG
    com.moira.itda.domain.suggest.approve.mapper: DEBUG
    com.moira.itda.domain.suggest.cancel.mapper: DEBUG
    com.moira.itda.domain.suggest.common.mapper: DEBUG
    com.moira.itda.domain.suggest.delete.mapper: DEBUG
    com.moira.itda.domain.suggest.list.mapper: DEBUG
    com.moira.itda.domain.suggest.reject.mapper: DEBUG
    com.moira.itda.domain.trade.add.mapper: DEBUG
    com.moira.itda.domain.trade.common.mapper: DEBUG
    com.moira.itda.domain.trade.delete.mapper: DEBUG
    com.moira.itda.domain.trade.list.mapper: DEBUG
    com.moira.itda.domain.trade.update.mapper: DEBUG
    com.moira.itda.domain.trade_target.mapper: DEBUG
    com.moira.itda.domain.trade_user_report.mapper: DEBUG
    com.moira.itda.domain.user.mypage.mapper: DEBUG
    com.moira.itda.domain.user.myplace.mapper: DEBUG
    com.moira.itda.domain.user.profile.mapper: DEBUG
    com.moira.itda.domain.user.support.mapper: DEBUG
    com.moira.itda.domain.user_activity_chat.mapper: DEBUG
    com.moira.itda.domain.user_activity_completed_trade.mapper: DEBUG

---

spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB

---

jwt:
  secret:
    key: ${JWT_SECRET_KEY}
  expiration-time:
    atk: ${JWT_EXPIRATION_TIME_ATK}
    rtk: ${JWT_EXPIRATION_TIME_RTK}

---

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION_STATIC}
    s3:
      bucketName: ${AWS_S3_BUCKET_NAME}

---

coolsms:
  apikey: ${COOLSMS_API_KEY}
  apisecret: ${COOLSMS_API_SECRET}
  fromnumber: ${COOLSMS_FROM_NUMBER}