spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

---

mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  configuration:
    jdbc-type-for-null: "NULL"
    map-underscore-to-camel-case: true

logging:
  level:
    com.moira.itda.domain.account.delete.mapper: DEBUG
    com.moira.itda.domain.account.login.mapper: DEBUG
    com.moira.itda.domain.account.logout.mapper: DEBUG
    com.moira.itda.domain.account.mypage.mapper: DEBUG
    com.moira.itda.domain.account.signup.mapper: DEBUG
    com.moira.itda.domain.admin_gacha.mapper: DEBUG
    com.moira.itda.domain.admin_user.mapper: DEBUG
    com.moira.itda.domain.admin_user_feedback.mapper: DEBUG
    com.moira.itda.domain.admin_user_report.mapper: DEBUG
    com.moira.itda.domain.chat_room.mapper: DEBUG
    com.moira.itda.domain.common.identify.mapper: DEBUG
    com.moira.itda.domain.common.image.mapper: DEBUG
    com.moira.itda.domain.common.refresh.mapper: DEBUG
    com.moira.itda.domain.gacha.mapper: DEBUG
    com.moira.itda.domain.gacha_common.mapper: DEBUG
    com.moira.itda.domain.gacha_list.mapper: DEBUG
    com.moira.itda.domain.gacha_trade_list.mapper: DEBUG
    com.moira.itda.domain.gacha_pick.mapper: DEBUG
    com.moira.itda.domain.notification.mapper: DEBUG
    com.moira.itda.domain.suggest.mapper: DEBUG
    com.moira.itda.domain.suggest_list.mapper: DEBUG
    com.moira.itda.domain.trade.mapper: DEBUG
    com.moira.itda.domain.trade_target.mapper: DEBUG
    com.moira.itda.domain.trade_user_report.mapper: DEBUG
    com.moira.itda.domain.user_activity_chat.mapper: DEBUG
    com.moira.itda.domain.user_activity_completed_trade.mapper: DEBUG
    com.moira.itda.domain.user_activity_suggest.mapper: DEBUG
    com.moira.itda.domain.user_feedback.mapper: DEBUG
    com.moira.itda.domain.user_place.mapper: DEBUG
    com.moira.itda.domain.user_simple_profile.mapper: DEBUG

---

spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB

---

jwt:
  secret:
    key: ${JWT_SECRET_KEY}
  expiration-time:
    atk: ${JWT_EXPIRATION_TIME_ATK}
    rtk: ${JWT_EXPIRATION_TIME_RTK}

---

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION_STATIC}
    s3:
      bucketName: ${AWS_S3_BUCKET_NAME}

---

coolsms:
  apikey: ${COOLSMS_API_KEY}
  apisecret: ${COOLSMS_API_SECRET}
  fromnumber: ${COOLSMS_FROM_NUMBER}