spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

---

mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  configuration:
    jdbc-type-for-null: "NULL"
    map-underscore-to-camel-case: true

logging:
  level:
    com.moira.itda.domain.admin.mapper: DEBUG
    com.moira.itda.domain.chat.mapper: DEBUG
    com.moira.itda.domain.common.mapper: DEBUG
    com.moira.itda.domain.gacha.mapper: DEBUG
    com.moira.itda.domain.gacha_common.mapper: DEBUG
    com.moira.itda.domain.gacha_list.mapper: DEBUG
    com.moira.itda.domain.gacha_pick.mapper: DEBUG
    com.moira.itda.domain.suggest.mapper: DEBUG
    com.moira.itda.domain.suggest_list.mapper: DEBUG
    com.moira.itda.domain.trade.mapper: DEBUG
    com.moira.itda.domain.trade_cancel.mapper: DEBUG
    com.moira.itda.domain.trade_target.mapper: DEBUG
    com.moira.itda.domain.trade_user_report.mapper: DEBUG
    com.moira.itda.domain.user.mapper: DEBUG
    com.moira.itda.domain.user_activity_suggest.mapper: DEBUG
    com.moira.itda.domain.user_feedback.mapper: DEBUG
    com.moira.itda.domain.user_place.mapper: DEBUG
    com.moira.itda.domain.user_simple_profile.mapper: DEBUG

---

spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB

---

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

---

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION_STATIC}
    s3:
      bucketName: ${AWS_S3_BUCKET_NAME}

---

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}